version: '3.10'
x-environment-defaults: &environment-defaults
  DEBUG: "False"
  DB_NAME: "store_shop_db"
  DB_USER: "store_user"
  DB_PASSWORD: "store_shop"
  DB_HOST: "postgres"
  DB_PORT: 5432

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  shop:
    build:
      context: .
    ports:
      - "8003:8000"
    depends_on:
      - postgres
    environment:
      <<: *environment-defaults
