# Generated by Django 5.0.1 on 2024-04-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'товар в корзине', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
